# Generated by Django 2.2.4 on 2019-08-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCliente', '0004_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appCliente.Pessoa'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(blank=True, to='appCliente.Product'),
        ),
    ]
